In [1]:
import numpy  as np
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from   sklearn.linear_model  import LinearRegression #线性回归
import sklearn.datasets as datasets#自带数据

In [12]:
x_train=np.array([[2,1],[1,-1]])
y_train=np.array([[3],[1]])

In [13]:
lrg=LinearRegression() #创建线性回归模型  ##线性回归
lrg.fit(x_train,y_train)#训练

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
coef_=lrg.coef_ 
np.dot(coef_,x_train)

array([[ 1.6, -0.4]])

In [16]:
lrg.predict([[3,-1]])

array([[ 1.8]])

In [17]:
x_train=np.array([[2,1,2,1],[2,3,2,3]]) #新的测试数据
y_train=np.array([1.2,3])

In [18]:
lrg=LinearRegression() #创建线性回归模型  #线性回归
lrg.fit(x_train,y_train)#训练

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
lrg.predict([[3,4,4,3]])#线性回归，样本太少，精确度不高

array([ 3.45])

In [20]:
lrg.coef_

array([  1.11022302e-16,   4.50000000e-01,   0.00000000e+00,
         4.50000000e-01])

In [35]:
#岭回归---样本少的情况，更加精准
from  sklearn.linear_model  import Ridge  #岭回归
x_train=np.array([[3,1],[2,1]])
y_train=np.array([1,3])
rigde=Ridge (alpha=1)
rigde.fit(x_train,y_train)
rigde.predict([[4,1]])

array([ 1.])

In [34]:
#逻辑回归
from  sklearn.linear_model  import  LinearRegression
x_train=np.array([[3,1],[2,1]])
y_train=np.array([1,3])
rigde= LinearRegression()
rigde.fit(x_train,y_train)
rigde.predict([[4,1]])

array([-1.])

In [42]:
#岭回归---样本少的情况，更加精准
from  sklearn.linear_model  import Ridge  #岭回归
x_train=np.array([[1,1],[3,3]])
y_train=np.array([1.5,3])
rigde=Ridge (alpha=1)
rigde.fit(x_train,y_train)
rigde.predict([[2,2]])

array([ 2.25])

In [41]:
#逻辑回归
from  sklearn.linear_model  import  LinearRegression
x_train=np.array([[1,1],[3,3]])
y_train=np.array([1.5,3])
rigde= LinearRegression()
rigde.fit(x_train,y_train)
rigde.predict([[2,2]])

array([ 2.25])