In [1]:
import numpy  as np
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from   sklearn.linear_model  import LinearRegression #线性回归
import sklearn.datasets as datasets#自带数据
#岭回归---样本少的情况，更加精准
from  sklearn.linear_model  import Ridge  #岭回归

In [2]:
x=[[0,0,0],[1,1,1]]    # 0*x+0.*y+0*z=0    x+y+z=1
y=[0,1] #2*x+2*y+2*z=2

In [3]:
lng=LinearRegression () #线性回归,考虑所有的特征，
lng.fit(x,y)
lng.predict(np.array([2,2,2])[np.newaxis,:])

array([ 2.])

In [25]:
ridge=Ridge  (alpha=0) #岭回归，与线性回归等价
ridge.fit(x,y) #alpha放弃特征的数量
ridge.predict(np.array([2,2,2])[np.newaxis,:])

c:\users\tsinghua-yincheng\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "


array([ 2.])

In [9]:
ridge.coef_

array([ 0.2,  0.2,  0.2])

In [10]:
ridge.intercept_

0.19999999999999996

In [7]:
np.array([2,2,2])[np.newaxis,:]

array([[2, 2, 2]])