In [3]:
import  numpy as np
np.random.binomial(100,0.5,20) #100次连续操作，其中0.5的概率的随机结果，接近50，20代表过程执行20次，得到20个结果

array([51, 51, 46, 56, 58, 55, 53, 43, 58, 48, 54, 54, 49, 49, 43, 48, 45,
       53, 54, 54])

In [4]:
np.random.binomial(100,0.5,5)

array([42, 58, 55, 48, 55])

In [5]:
np.random.binomial(10000,0.5,5)

array([5052, 5033, 4997, 5092, 5065])

In [6]:
from  scipy  import  stats  #科学计算 scikilearn
stats.binom.pmf(20,100,0.5) #100次仍硬币，其中20次朝上的g概率

4.2281632676012532e-10

In [7]:
from  scipy  import  stats  #科学计算 scikilearn
stats.binom.pmf(50,100,0.5)

0.079589237387178879

In [8]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
path=r"C:\Users\Tsinghua-yincheng\Desktop\SZday79\code\codedata\return300.csv"
Return300=pd.read_csv(path) #读取数据
Return300

date  return  sig
0      2014/1/2 -0.3454    0
1      2014/1/3 -1.3436    0
2      2014/1/6 -2.2762    0
3      2014/1/7 -0.0284    0
4      2014/1/8  0.1747    1
5      2014/1/9 -0.8783    0
6     2014/1/10 -0.7817    0
7     2014/1/13 -0.5067    0
8     2014/1/14  0.8737    1
9     2014/1/15 -0.1765    0
10    2014/1/16  0.1314    1
11    2014/1/17 -1.5081    0
12    2014/1/20 -0.5736    0
13    2014/1/21  0.9888    1
14    2014/1/22  2.5778    1
15    2014/1/23 -0.5307    0
16    2014/1/24  0.6178    1
17    2014/1/27 -1.3252    0
18    2014/1/28  0.1776    1
19    2014/1/29  0.3571    1
20    2014/1/30 -1.1371    0
21     2014/2/7  0.4555    1
22    2014/2/10  2.4882    1
23    2014/2/11  0.7950    1
24    2014/2/12  0.2487    1
25    2014/2/13 -0.5103    0
26    2014/2/14  0.7028    1
27    2014/2/17  0.7001    1
28    2014/2/18 -1.2634    0
29    2014/2/19  1.1485    1
..          ...     ...  ...
215  2014/11/20 -0.0049    0
216  2014/11/21  1.8271    1
217  2014/11/24  2.5471    1
218  2014/11/25  1.3703    1
219  2014/11/26  1.3948    1
220  2014/11/27  1.1558    1
221  2014/11/28  1.9724    1
222   2014/12/1  0.3914    1
223   2014/12/2  3.6927    1
224   2014/12/3  1.4914    1
225   2014/12/4  4.6099    1
226   2014/12/5  0.6615    1
227   2014/12/8  4.0960    1
228   2014/12/9 -4.4873    0
229  2014/12/10  3.6896    1
230  2014/12/11 -1.1961    0
231  2014/12/12  0.3209    1
232  2014/12/15  0.7516    1
233  2014/12/16  2.6785    1
234  2014/12/17  1.7314    1
235  2014/12/18 -0.4366    0
236  2014/12/19  1.1130    1
237  2014/12/22  0.3344    1
238  2014/12/23 -2.0491    0
239  2014/12/24 -2.8433    0
240  2014/12/25  3.2514    1
241  2014/12/26  3.3105    1
242  2014/12/29  0.2791    1
243  2014/12/30  0.0607    1
244  2014/12/31  2.2025    1

[245 rows x 3 columns]

In [9]:
ret=Return300.iloc[:,1]
ret.head()

0   -0.3454
1   -1.3436
2   -2.2762
3   -0.0284
4    0.1747
Name: return, dtype: float64

In [10]:
p=len(ret[ret>0])/len(ret) #上涨的概率
p

0.5306122448979592

In [11]:
1-p

0.4693877551020408

In [13]:
p=len(ret[ret<0])/len(ret)  #下跌的概率
p

0.46938775510204084

In [14]:
stats.binom.pmf(10,20,p)#交易20天，连续10天下跌的概率

0.16970271499061987

In [15]:
stats.binom.pmf(10,20,(1-p))

0.1697027149906197