In [1]:
import  numpy as np

In [2]:
Normal=np.random.normal(size=15)

In [3]:
Normal  #正态分布的15个数

array([-0.99281434,  1.71347238, -0.70491215, -0.19593888, -0.45910435,
        0.64557703, -0.50591047, -0.12930176,  0.58913069,  1.23261979,
        1.93235911,  0.91413595, -0.91806757, -0.80434847, -1.31462455])

In [4]:
Normal=np.random.normal(size=8)
Normal

array([ 0.12922603,  0.915237  ,  0.37680867,  1.35692316,  0.41481098,
       -0.46535962, -0.60414585, -1.68714633])

In [5]:
from scipy import stats
stats.norm.pdf(Normal ) #计算随机数的密度

array([ 0.39562511,  0.26243078,  0.37160236,  0.15888752,  0.36605466,
        0.35800142,  0.33239388,  0.09611884])

In [6]:
from scipy import stats
stats.norm.cdf(Normal ) #计算随机数的密度

array([ 0.5514106 ,  0.81996639,  0.6468421 ,  0.91259719,  0.66085986,
        0.32083697,  0.27287334,  0.04578761])

In [7]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
path=r"C:\Users\Tsinghua-yincheng\Desktop\SZday79\code\codedata\return300.csv"
Return300=pd.read_csv(path) #读取数据
Return300

date  return  sig
0      2014/1/2 -0.3454    0
1      2014/1/3 -1.3436    0
2      2014/1/6 -2.2762    0
3      2014/1/7 -0.0284    0
4      2014/1/8  0.1747    1
5      2014/1/9 -0.8783    0
6     2014/1/10 -0.7817    0
7     2014/1/13 -0.5067    0
8     2014/1/14  0.8737    1
9     2014/1/15 -0.1765    0
10    2014/1/16  0.1314    1
11    2014/1/17 -1.5081    0
12    2014/1/20 -0.5736    0
13    2014/1/21  0.9888    1
14    2014/1/22  2.5778    1
15    2014/1/23 -0.5307    0
16    2014/1/24  0.6178    1
17    2014/1/27 -1.3252    0
18    2014/1/28  0.1776    1
19    2014/1/29  0.3571    1
20    2014/1/30 -1.1371    0
21     2014/2/7  0.4555    1
22    2014/2/10  2.4882    1
23    2014/2/11  0.7950    1
24    2014/2/12  0.2487    1
25    2014/2/13 -0.5103    0
26    2014/2/14  0.7028    1
27    2014/2/17  0.7001    1
28    2014/2/18 -1.2634    0
29    2014/2/19  1.1485    1
..          ...     ...  ...
215  2014/11/20 -0.0049    0
216  2014/11/21  1.8271    1
217  2014/11/24  2.5471    1
218  2014/11/25  1.3703    1
219  2014/11/26  1.3948    1
220  2014/11/27  1.1558    1
221  2014/11/28  1.9724    1
222   2014/12/1  0.3914    1
223   2014/12/2  3.6927    1
224   2014/12/3  1.4914    1
225   2014/12/4  4.6099    1
226   2014/12/5  0.6615    1
227   2014/12/8  4.0960    1
228   2014/12/9 -4.4873    0
229  2014/12/10  3.6896    1
230  2014/12/11 -1.1961    0
231  2014/12/12  0.3209    1
232  2014/12/15  0.7516    1
233  2014/12/16  2.6785    1
234  2014/12/17  1.7314    1
235  2014/12/18 -0.4366    0
236  2014/12/19  1.1130    1
237  2014/12/22  0.3344    1
238  2014/12/23 -2.0491    0
239  2014/12/24 -2.8433    0
240  2014/12/25  3.2514    1
241  2014/12/26  3.3105    1
242  2014/12/29  0.2791    1
243  2014/12/30  0.0607    1
244  2014/12/31  2.2025    1

[245 rows x 3 columns]

In [8]:
ret=Return300.iloc[:,1] #假定数据属于正态分布
ret.head()

0   -0.3454
1   -1.3436
2   -2.2762
3   -0.0284
4    0.1747
Name: return, dtype: float64

In [11]:
HS300_retmen=ret.mean()#均值
HS300_retmen

0.1774236734693877

In [12]:
HS300_retvar=ret.var()#方差
HS300_retvar

1.471205934847106

In [13]:
stats.norm.pdf(0.05,HS300_retmen,HS300_retvar**0.5) #计算正态分布

0.32709718873189186

In [14]:
stats.norm.pdf(0.95,HS300_retmen,HS300_retvar**0.5)

0.26851949419703119

In [15]:
stats.norm.pdf(0.5,HS300_retmen,HS300_retvar**0.5)

0.31747895109673391