In [2]:
import numpy  as np #导入模块

In [3]:
array1=np.array([1,2,3,4,5]) #创建1维数组

In [4]:
array1

array([1, 2, 3, 4, 5])

In [5]:
array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])#创建2维数组

In [6]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
array3=np.array([1,2,3,4,5],ndmin=2) #ndmin至少2维

In [8]:
array3

array([[1, 2, 3, 4, 5]])

In [9]:
array4=np.array([1,2,3,4,5],dtype="complex") #实数
array4

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j])