In [1]:
import numpy as np
a=np.arange(12)
a=a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for  x   in np.nditer(a): #遍历每一个元素
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print(a.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [8]:
b=a.T
for  x   in np.nditer(b): #遍历每一个元素,与矩阵的shape无关
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a.shape=(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
for  x   in np.nditer(a): #遍历每一个元素,与矩阵的shape无关
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
b=a.copy()#拷贝数组

In [14]:
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [15]:
c=b.copy(order='C') #拷贝数组，制定顺序
for  x  in  np.nditer(c): #从左往右，从上往下
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
c=b.copy(order='F')
for  x  in  np.nditer(c):#从上往下 从左往右，
    print(x)

0
6
1
7
2
8
3
9
4
10
5
11


In [17]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
for  x  in  np.nditer(a,order="C"):#从左往右，从上往下 
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [19]:
for  x  in  np.nditer(a,order="F"):#从上往下 从左往右，
    print(x)

0
6
1
7
2
8
3
9
4
10
5
11


In [20]:
for  x  in  np.nditer(a):#从上往下 从左往右，
    x=10
    print(x)

10
10
10
10
10
10
10
10
10
10
10
10


In [21]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
for  x  in  np.nditer(a,op_flags=["readwrite"]):#从上往下 从左往右 ，
    x[...]=2*x
a   #op_flags=["readwrite"]修改原来的数据

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [23]:
for  x  in  np.nditer(a):
    print(x)

0
2
4
6
8
10
12
14
16
18
20
22


In [24]:
for  x  in  np.nditer(a,flags =  ['external_loop']):
    print(x)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [25]:
for  x  in  np.nditer(a,flags =  ['c_index']):
    print(x)

0
2
4
6
8
10
12
14
16
18
20
22


In [26]:
for  x  in  np.nditer(a,flags =  ['f_index']):
    print(x)

0
2
4
6
8
10
12
14
16
18
20
22


In [27]:
a

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [28]:
b=np.array([1,1,1,1,1,1])

In [29]:
print(a+b)

[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]


In [31]:
for  x,y  in  np.nditer([a,b]):#广播迭代，循环迭代，烈数相同
    print(x,y)

0 1
2 1
4 1
6 1
8 1
10 1
12 1
14 1
16 1
18 1
20 1
22 1
