In [9]:
import numpy as np
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y) # 对 y 广播 x
b.index
print(b.__next__())#循环下一个
print(b.__next__())
print(b.__next__())
print(b.__next__())
print(b.__next__())
print(b.__next__())
print(b.__next__())
print(b.__next__())
print(b.__next__())
print(b.index) #索引位置

(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)
9


In [8]:
print (b.shape) #二维数组

(3, 3)


In [10]:
b = np.broadcast(x,y)
c = np.empty(b.shape) #清空 数组，实数，

In [12]:
b,c

(<numpy.broadcast at 0xfe25809680>,
 array([[  0.00000000e+000,   4.52564132e-321,   2.47032823e-323],
        [  5.39281897e-312,   0.00000000e+000,   2.47032823e-323],
        [  5.39282126e-312,   0.00000000e+000,   3.23815565e-319]]))

In [13]:
c.shape

(3, 3)

In [15]:
c.flat=[u+v for (u,v) in  b ]  #数组的加法
c

array([[ 5.,  6.,  7.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.]])

In [16]:
a=np.arange(4).reshape(1,4)
a

array([[0, 1, 2, 3]])

In [19]:
print(np.broadcast_to(a,(10,4))) #实现数组的复制，要求列数相同

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [20]:
x=np.array(([1,2],[3,4]))

In [21]:
x #二唯数组

array([[1, 2],
       [3, 4]])

In [22]:
y=np.expand_dims(x,axis=0) #插入一个坐标轴
print(y)

[[[1 2]
  [3 4]]]


In [23]:
y=np.expand_dims(x,axis=1)
print(y)

[[[1 2]]

 [[3 4]]]


In [24]:
y=np.expand_dims(x,axis=2)
print(y)

[[[1]
  [2]]

 [[3]
  [4]]]


In [29]:
x=np.arange(27).reshape(1,3,9)
x

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [30]:
print(x.shape)

(1, 3, 9)


In [31]:
y=np.squeeze(x) #只有外层只有一个元素，可以删除一个维度，
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [32]:
y.shape

(3, 9)