In [1]:
import  numpy as np
a=np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [3]:
a=a.reshape(4,5) #调整大小
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [4]:
for  x  in  np.nditer(a): #循环
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95


In [5]:
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [6]:
a.T

array([[ 0, 25, 50, 75],
       [ 5, 30, 55, 80],
       [10, 35, 60, 85],
       [15, 40, 65, 90],
       [20, 45, 70, 95]])

In [8]:
a=np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [9]:
print(a.flat[5])

5


In [10]:
print(a.flat[15])

15


In [11]:
print(a.flat[0]) # 返回展开数组中的下标的对应元素

0


In [12]:
a.flat[0]=1000
a

array([[1000,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19]])

In [13]:
a.flatten()

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [14]:
a.flatten(order="F") #副本

array([1000,   10,    1,   11,    2,   12,    3,   13,    4,   14,    5,
         15,    6,   16,    7,   17,    8,   18,    9,   19])

In [15]:
a.flatten(order="F").flat[0]=5000

In [16]:
a

array([[1000,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19]])

In [17]:
print(a.ravel()) #返回折叠好的一维数组

[1000    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19]


In [18]:
print(a.ravel(order = 'F')) #折叠，指定顺序

[1000   10    1   11    2   12    3   13    4   14    5   15    6   16    7
   17    8   18    9   19]


In [19]:
a=np.arange(0,100,5)
a.shape=(4,5)
a

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [20]:
print(np.transpose(a)) #矩阵转置

[[ 0 25 50 75]
 [ 5 30 55 80]
 [10 35 60 85]
 [15 40 65 90]
 [20 45 70 95]]


In [21]:
print(a.T)

[[ 0 25 50 75]
 [ 5 30 55 80]
 [10 35 60 85]
 [15 40 65 90]
 [20 45 70 95]]


In [22]:
a=np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
print(np.rollaxis(a,2,1))

[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [25]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
print(np.rollaxis(a,2)) #默认到0

[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [27]:
'''

其中：

+   `arr`：输入数组
+   `axis`：要向后滚动的轴，其它轴的相对位置不会改变
+   `start`：默认为零，表示完整的滚动。会滚动到特定位置。
[x][y][z]
[y][x][z] 0
[z][x][y] 2
[x][z][y] 1

[y][x][z] 0  0
[y][z][x] 0  2

'''

'\n\n其中：\n\n+   `arr`：输入数组\n+   `axis`：要向后滚动的轴，其它轴的相对位置不会改变\n+   `start`：默认为零，表示完整的滚动。会滚动到特定位置。\n[x][y][z]\n[y][x][z] 0\n[z][x][y] 2\n[x][z][y] 1\n\n[y][x][z] 0  0\n[y][z][x] 0  2\n\n'

In [28]:
b=np.array([1,2,3,4,5,6])
b=b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print(np.swapaxes(b,1,0)) #交换x,y   x=0,y=1,z=2

[[1 4]
 [2 5]
 [3 6]]


In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
print(np.rollaxis(b,1))

[[1 4]
 [2 5]
 [3 6]]


In [33]:
print(np.rollaxis(b,1,1))

[[1 2 3]
 [4 5 6]]
