In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [5]:
print(np.concatenate((a,b))) #拼接，按照列拼接

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
print(np.concatenate((a,b),axis=1)) #按照行拼接

[[1 2 5 6]
 [3 4 7 8]]


In [7]:
np.stack((a,b),0) #此函数沿新轴连接数组序列。2个2维变成一个3维数组

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
np.stack((a,b),1)#此函数沿新轴连接数组序列。2个2维变成一个3维数组

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [9]:
np.hstack((a,b)) #保持2维数组，按照列 叠加

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
np.vstack((a,b))#保持2维数组，按照行 叠加

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
b=np.split(a,10)
b #切割为10个数组

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [15]:
c=np.split(a,[30,60,80]) #按照位置切割
c

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
        47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99])]

In [18]:
a=np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
b=np.hsplit(a,2) #按照列切割
b

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]), array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [21]:
b=np.hsplit(a,5) #按照列切割
b

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41],
        [50, 51],
        [60, 61],
        [70, 71],
        [80, 81],
        [90, 91]]), array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43],
        [52, 53],
        [62, 63],
        [72, 73],
        [82, 83],
        [92, 93]]), array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45],
        [54, 55],
        [64, 65],
        [74, 75],
        [84, 85],
        [94, 95]]), array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47],
        [56, 57],
        [66, 67],
        [76, 77],
        [86, 87],
        [96, 97]]), array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49],
        [58, 59],
        [68, 69],
        [78, 79],
        [88, 89],
        [98, 99]])]

In [23]:
b=np.vsplit(a,2) #按照行切割，切割必须可以整除
b

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [25]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b=np.resize(a,(3,3)) #改变数组形状

In [29]:
a.shape,b.shape

((9,), (3, 3))

In [31]:
b=np.resize(a,(3,4)) #此函数返回指定大小的新数组。 如果新大小大于原始大小，则包含原始数组中的元素的重复副本。
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [34]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b=np.append(a,10) #增加一个元素，拷贝到新数组
b

array([ 1,  2,  3,  4,  5,  6, 10])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
b=np.append(a,[10,11,12]) #增加一个数组，拷贝到新数组
b

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b=np.append(a,[[7,8,9]],axis=0) #按照行添加
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b=np.append(a,[[17,18,19],[100,101,102]],axis=1) #按照面添加
b

array([[  1,   2,   3,  17,  18,  19],
       [  4,   5,   6, 100, 101, 102]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.insert(a,2,[100,101]) #新建一个数组，按照数据位置插入

array([  1,   2, 100, 101,   3,   4,   5,   6])

In [44]:
np.insert(a,5,[100,101])

array([  1,   2,   3,   4,   5, 100, 101,   6])

In [46]:
np.insert(a,1,[100000],axis=0) #插入一个整行

array([[     1,      2,      3],
       [100000, 100000, 100000],
       [     4,      5,      6]])

In [47]:
np.insert(a,1,[1000,10000,100000],axis=0) #插入一个整行

array([[     1,      2,      3],
       [  1000,  10000, 100000],
       [     4,      5,      6]])

In [51]:
np.insert(a,1,[[1000,10000],[1000,10000]],axis=1)#插入一个面

array([[    1,  1000,  1000,     2,     3],
       [    4, 10000, 10000,     5,     6]])

In [53]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
print(np.delete(a,5))

[ 0  1  2  3  4  6  7  8  9 10 11]


In [56]:
print(np.delete(a,0,axis=0)) #删除含有0的哪一行

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
print(np.delete(a,1,axis=1))#删除含有1的那一列

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [59]:
a=np.array([1,2,3,4,1,2,3,4,5,6])
a

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [60]:
print(np.unique(a)) #去掉重复

[1 2 3 4 5 6]


In [61]:
u,index=np.unique(a,return_index=True) #原有数组的索引
index

array([0, 1, 2, 3, 8, 9], dtype=int64)

In [62]:
u

array([1, 2, 3, 4, 5, 6])

In [64]:
print(a[index]) #原有数组选择不重复的索引数据

[1 2 3 4 5 6]


In [65]:
u,indexid=np.unique(a,return_inverse=True) #下标表示重复
indexid

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 5], dtype=int64)

In [66]:
a[indexid] #根据下标重建数组

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2])

In [68]:
u,nums=np.unique(a,return_counts=True) #返回重复次数
nums

array([2, 2, 2, 2, 1, 1], dtype=int64)