In [1]:
import  numpy as np

In [3]:
myarray=np.array([0,30,60,45,90,150,180,360])
myarray

array([  0,  30,  60,  45,  90, 150, 180, 360])

In [4]:
np.pi  #180

3.141592653589793

In [5]:
np.sin(myarray*np.pi/180) #计算sin

array([  0.00000000e+00,   5.00000000e-01,   8.66025404e-01,
         7.07106781e-01,   1.00000000e+00,   5.00000000e-01,
         1.22464680e-16,  -2.44929360e-16])

In [6]:
np.cos(myarray*np.pi/180) #计算cos

array([  1.00000000e+00,   8.66025404e-01,   5.00000000e-01,
         7.07106781e-01,   6.12323400e-17,  -8.66025404e-01,
        -1.00000000e+00,   1.00000000e+00])

In [7]:
np.tan(myarray*np.pi/180) #计算tan

array([  0.00000000e+00,   5.77350269e-01,   1.73205081e+00,
         1.00000000e+00,   1.63312394e+16,  -5.77350269e-01,
        -1.22464680e-16,  -2.44929360e-16])

In [8]:
np.arccos(myarray*np.pi/180) #asin

c:\users\tsinghua-yincheng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


array([ 1.57079633,  1.01972674,         nan,  0.66745722,         nan,
               nan,         nan,         nan])

In [10]:
np.arcsin(myarray*np.pi/180) #acos

c:\users\tsinghua-yincheng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([ 0.        ,  0.55106958,         nan,  0.90333911,         nan,
               nan,         nan,         nan])

In [11]:
sin=np.sin(myarray*np.pi/180)

In [12]:
inv=np.arcsin(sin)
inv

array([  0.00000000e+00,   5.23598776e-01,   1.04719755e+00,
         7.85398163e-01,   1.57079633e+00,   5.23598776e-01,
         1.22464680e-16,  -2.44929360e-16])

In [13]:
np.degrees(inv) #转化为角度

array([  0.00000000e+00,   3.00000000e+01,   6.00000000e+01,
         4.50000000e+01,   9.00000000e+01,   3.00000000e+01,
         7.01670930e-15,  -1.40334186e-14])

In [18]:
myarr=np.array([1.1,5.5,12.3,25.1,0.78,29.3])
myarr

array([  1.1 ,   5.5 ,  12.3 ,  25.1 ,   0.78,  29.3 ])

In [15]:
np.around(myarr) #正常四舍五入

array([  1.,   6.,  12.,  25.,   1.,  29.])

In [16]:
np.around(myarr,decimals=1) #保留一位小数

array([  1.1,   5.5,  12.3,  25. ,   0.8,  29.3])

In [19]:
np.around(myarr,decimals=-1)#个位数清零   5.0 4.9999999999= 5.1

array([  0.,  10.,  10.,  30.,   0.,  30.])

In [20]:
a = np.array([-1.7,  1.5,  -0.2,  0.6,  10])  
np.floor(a) #此函数返回不大于输入参数的最大整数。

array([ -2.,   1.,  -1.,   0.,  10.])

In [21]:
a = np.array([-1.7,  1.5,  -0.2,  0.6,  10])  
np.ceil(a)#返回大于输入数据的第一个整数

array([ -1.,   2.,  -0.,   1.,  10.])