In [1]:
import  numpy as np
Array1=np.arange(16).reshape(4,4)
Array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [2]:
Array2=np.array([10,20,30,40])
Array2

array([10, 20, 30, 40])

In [3]:
np.add(Array1,Array2) #数组的加法

array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51],
       [22, 33, 44, 55]])

In [4]:
Array3=np.array([[10,20,30,40],[10,20,30,40],[10,20,30,40],[10,20,30,40]])
Array3

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [5]:
np.add(Array1,Array3) #数组的加法

array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51],
       [22, 33, 44, 55]])

In [6]:
np.subtract(Array1,Array2) #数组的减法

array([[-10, -19, -28, -37],
       [ -6, -15, -24, -33],
       [ -2, -11, -20, -29],
       [  2,  -7, -16, -25]])

In [7]:
np.multiply(Array1,Array2) #数组的乘法

array([[  0,  20,  60, 120],
       [ 40, 100, 180, 280],
       [ 80, 180, 300, 440],
       [120, 260, 420, 600]])

In [8]:
np.divide(Array1,Array2) #除法

array([[ 0.        ,  0.05      ,  0.06666667,  0.075     ],
       [ 0.4       ,  0.25      ,  0.2       ,  0.175     ],
       [ 0.8       ,  0.45      ,  0.33333333,  0.275     ],
       [ 1.2       ,  0.65      ,  0.46666667,  0.375     ]])

In [9]:
Array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.reciprocal(Array1)

c:\users\tsinghua-yincheng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.
c:\users\tsinghua-yincheng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[-2147483648,           1,           0,           0],
       [          0,           0,           0,           0],
       [          0,           0,           0,           0],
       [          0,           0,           0,           0]], dtype=int32)

In [11]:
Array1=np.arange(16,dtype=float).reshape(4,4)
Array1

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.]])

In [13]:
np.reciprocal(Array1) #倒数，a*b=1,b就是a的倒数

c:\users\tsinghua-yincheng\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[        inf,  1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909],
       [ 0.08333333,  0.07692308,  0.07142857,  0.06666667]])

In [14]:
a=np.array([100,200,300])
b=np.array([1,2,3])

In [15]:
np.power(a,2) #求平方计算

array([10000, 40000, 90000], dtype=int32)

In [16]:
np.power(a,b)

array([     100,    40000, 27000000], dtype=int32)

In [17]:
a=np.array([100,200,300])
b=np.array([1,2,3])
np.mod(a,b)

array([0, 0, 0], dtype=int32)

In [18]:
a=np.array([100,200,300])
b=np.array([11,12,13])
np.mod(a,b)#求模计算

array([1, 8, 1], dtype=int32)

In [19]:
complex=np.array([1-5.6j,1+2j,11,1+1j])

In [20]:
np.real(complex)

array([  1.,   1.,  11.,   1.])

In [21]:
np.imag(complex)

array([-5.6,  2. ,  0. ,  1. ])

In [22]:
np.angle(complex)

array([-1.39408747,  1.10714872,  0.        ,  0.78539816])