In [1]:
import  numpy as np

In [2]:
myarray=np.array([[11,21,2],[111,11,222],[33,44,32]])
myarray

array([[ 11,  21,   2],
       [111,  11, 222],
       [ 33,  44,  32]])

In [4]:
np.amax(myarray) #极大

222

In [5]:
np.amin(myarray)#极小

2

In [6]:
np.amin(myarray,0)  #每一列的最小值，

array([11, 11,  2])

In [7]:
np.amin(myarray,1)  #每一行的最小值，

array([ 2, 11, 32])

In [8]:
np.amax(myarray,0) #极大每一列

array([111,  44, 222])

In [9]:
np.amax(myarray,1)#每一行

array([ 21, 222,  44])

In [11]:
np.ptp(myarray)  #最大与最小之差

220

In [12]:
np.ptp(myarray,0) #每一列

array([100,  33, 220])

In [13]:
np.ptp(myarray,1)##每一行

array([ 19, 211,  12])

In [24]:
np.percentile(myarray,70) #按照人群的比例求百分比

39.599999999999994

In [25]:
np.percentile(myarray,70,axis=0) #每一列

array([  64.2,   30.2,  108. ])

In [27]:
np.percentile(myarray,70,axis=1)  #每一行

array([  15. ,  155.4,   37.4])

In [28]:
np.median(myarray)#取中间数

32.0

In [29]:
np.median(myarray,axis=0) #每一列

array([ 33.,  21.,  32.])

In [30]:
np.median(myarray,axis=1)#每一行

array([  11.,  111.,   33.])

In [31]:
myarray

array([[ 11,  21,   2],
       [111,  11, 222],
       [ 33,  44,  32]])

In [32]:
np.mean(myarray)#取平均值

54.111111111111114

In [33]:
np.mean(myarray,axis=0)#取平均值，列

array([ 51.66666667,  25.33333333,  85.33333333])

In [34]:
np.mean(myarray,axis=1)#取平均值，行

array([  11.33333333,  114.66666667,   36.33333333])

In [35]:
a=np.array([6,7,8,9,10])#权重平均值
b=np.array([10,1,2,3,4])
np.average(a,weights=b)

7.5

In [36]:
np.std([4,4,4,4]) #标准差，平均程度  ，标准差是方差的平方根

0.0

In [38]:
np.std([74,84,94,104])

11.180339887498949

In [39]:
np.var([4,4,4,4])#方差，平均程度

0.0

In [40]:
np.var([4,4,4,1114])

231018.75