In [1]:
import  numpy as np

In [5]:
a=np.array([[3,9,0],[1,8,2]])
a

array([[3, 9, 0],
       [1, 8, 2]])

In [8]:
print(np.sort(a)) #按照行排序

[[0 3 9]
 [1 2 8]]


In [9]:
print(np.sort(a,axis=0)) #按照列排序

[[1 8 0]
 [3 9 2]]


In [12]:
dt=np.dtype([("name","S10"),("age",int),("tall",int)])
a=np.array([("fengjie",33,160),("chunge",28,150),("furong",38,170)],
           dtype=dt)

In [13]:
np.sort(a,order="name")

array([(b'chunge', 28, 150), (b'fengjie', 33, 160), (b'furong', 38, 170)], 
      dtype=[('name', 'S10'), ('age', '<i4'), ('tall', '<i4')])

In [14]:
np.sort(a,order="age")

array([(b'chunge', 28, 150), (b'fengjie', 33, 160), (b'furong', 38, 170)], 
      dtype=[('name', 'S10'), ('age', '<i4'), ('tall', '<i4')])

In [15]:
np.sort(a,order="tall")

array([(b'chunge', 28, 150), (b'fengjie', 33, 160), (b'furong', 38, 170)], 
      dtype=[('name', 'S10'), ('age', '<i4'), ('tall', '<i4')])

In [16]:
np.sort(a,kind="heapsort",order="tall") #堆排序

array([(b'chunge', 28, 150), (b'fengjie', 33, 160), (b'furong', 38, 170)], 
      dtype=[('name', 'S10'), ('age', '<i4'), ('tall', '<i4')])

In [17]:
np.sort(a,kind="mergesort",order="tall") #归并排序

array([(b'chunge', 28, 150), (b'fengjie', 33, 160), (b'furong', 38, 170)], 
      dtype=[('name', 'S10'), ('age', '<i4'), ('tall', '<i4')])

In [18]:
'''
NumPy中提供了各种排序相关功能。 这些排序函数实现不同的排序算法，每个排序算法的特征在于执行速度，最坏情况性能，所需的工作空间和算法的稳定性。 下表显示了三种排序算法的比较。

| 种类 | 速度 | 最坏情况 | 工作空间 | 稳定性 |
| --- | --- | --- | --- | --- |
| `'quicksort'`（快速排序） | 1 | `O(n^2)` | 0 | 否 |
| `'mergesort'`（归并排序） | 2 | `O(n*log(n))` | ~n/2 | 是 |
| `'heapsort'`（堆排序） | 3 | `O(n*log(n))` | 0 | 否 |

## `numpy.sort()`

`sort()`函数返回输入数组的排序副本。 它有以下参数：

```
numpy.sort(a, axis, kind, order)

```

其中：

| 序号 | 参数及描述 |
| --- | --- |
| 1. | `a` 要排序的数组 |
| 2. | `axis` 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序 |
| 3. | `kind` 默认为`'quicksort'`（快速排序） |
| 4. | `order` 如果数组包含字段，则是要排序的字段 |
'''

"\nNumPy中提供了各种排序相关功能。 这些排序函数实现不同的排序算法，每个排序算法的特征在于执行速度，最坏情况性能，所需的工作空间和算法的稳定性。 下表显示了三种排序算法的比较。\n\n| 种类 | 速度 | 最坏情况 | 工作空间 | 稳定性 |\n| --- | --- | --- | --- | --- |\n| `'quicksort'`（快速排序） | 1 | `O(n^2)` | 0 | 否 |\n| `'mergesort'`（归并排序） | 2 | `O(n*log(n))` | ~n/2 | 是 |\n| `'heapsort'`（堆排序） | 3 | `O(n*log(n))` | 0 | 否 |\n\n## `numpy.sort()`\n\n`sort()`函数返回输入数组的排序副本。 它有以下参数：\n\n```\nnumpy.sort(a, axis, kind, order)\n\n```\n\n其中：\n\n| 序号 | 参数及描述 |\n| --- | --- |\n| 1. | `a` 要排序的数组 |\n| 2. | `axis` 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序 |\n| 3. | `kind` 默认为`'quicksort'`（快速排序） |\n| 4. | `order` 如果数组包含字段，则是要排序的字段 |\n"

In [19]:
x=np.array([2,1,4,3])
x

array([2, 1, 4, 3])

In [20]:
y=np.argsort(x) #索引排序
y

array([1, 0, 3, 2], dtype=int64)

In [21]:
x[y] #取得有序

array([1, 2, 3, 4])

In [23]:
x

array([2, 1, 4, 3])

In [24]:
np.argmax(x) #最大的元素的索引

2

In [25]:
np.argmin(x)#最小元素的索引

1

In [26]:
np.nonzero(x) #数组中不为0的索引

(array([0, 1, 2, 3], dtype=int64),)

In [27]:
np.nonzero(np.array([0,1,0,1]))#数组中不为0的索引

(array([1, 3], dtype=int64),)

In [28]:
nm =  ('raju','anil','ravi','amar') 
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.') 
ind = np.lexsort((dv,nm))   
print(ind)

[3 1 0 2]


In [29]:
[nm[i]  +  ", "  + dv[i]  for i in ind]

['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']

In [33]:
nm =  ('B','A','D','C') 
dv =  ('1',  '2',  '3',  '4') 
ind = np.lexsort((dv,nm))    #得到排序以后的索引
print(ind)  #一一对应的关系不变

[1 0 3 2]


In [34]:
[nm[i]  +  ", "  + dv[i]  for i in ind]

['A, 2', 'B, 1', 'C, 4', 'D, 3']

In [35]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])  
np.argmax(a)

7

In [36]:
np.argmin(a)

5

In [41]:
print(np.argmax(a,axis=0)) #取得最大值按照列

[1 2 0]


In [42]:
print(a)

[[30 40 70]
 [80 20 10]
 [50 90 60]]


In [43]:
print(np.argmax(a,axis=1)) #取得最大值按照行

[2 0 1]


In [44]:
print(np.argmin(a,axis=0))

[0 1 1]


In [45]:
print(np.argmin(a,axis=1))

[0 2 0]


In [47]:
x = np.arange(9.).reshape(3,  3)  
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [49]:
y = np.where(x >  3)  
y #索引  [1, 1, 2, 2, 2],[1, 2, 0, 1, 2]->[11，12，20，21，22]

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [50]:
cond=np.mod(x,2)==0 #条件
np.extract(cond,x) #挖掘所有条件成立的

array([ 0.,  2.,  4.,  6.,  8.])