In [1]:
import numpy  as np #导入模块
data1=np.dtype(np.int32) #4G  数组的索引大小32   2^1024  G M K 
print(data1)

int32


In [4]:
data1=np.dtype("i2") #4G  数组的索引大小32   2^1024  G M K 
print(data1)  #年龄-int8 0-256    #QQ数据索引int64
##int8，int16，int32，int64 可替换为等价的字符串 'i1'，'i2'，'i4'，以及其他。

int16


In [5]:
data1=np.dtype(">i4") #4G  数组的索引大小32   2^1024  G M K 
print(data1)

>i4


In [8]:
datatall=np.dtype([("tall1",np.int16),("tall2",np.int16)]) #描述数据

In [9]:
print(datatall)

[('tall1', '<i2'), ('tall2', '<i2')]


In [10]:
dt=np.dtype([(("age",np.int8))]) #创建一个复合类型，对于数据的藐视
ageArray=np.array([(10,),(20,),(30,)],dtype=dt) #创建一个数组，为dtype,
ageArray  #  (10,)  <---->dt

array([(10,), (20,), (30,)], 
      dtype=[('age', 'i1')])

In [11]:
ageArray["age"]

array([10, 20, 30], dtype=int8)

In [12]:
student=np.dtype([("name","S20"),("age","i4"),("money","f4")]) #自定义数据类型ng
student

dtype([('name', 'S20'), ('age', '<i4'), ('money', '<f4')])

In [13]:
studentArray=np.array([("huangjian",88,12345678883.34),
                       ("xiaohuangjian",58,12345678883.34)],
                      dtype=student
                      ) #创建自定义类型的数组

In [14]:
studentArray

array([(b'huangjian', 88,   1.23456788e+10),
       (b'xiaohuangjian', 58,   1.23456788e+10)], 
      dtype=[('name', 'S20'), ('age', '<i4'), ('money', '<f4')])

In [15]:
studentArray["name"]

array([b'huangjian', b'xiaohuangjian'], 
      dtype='|S20')

In [16]:
studentArray["age"]

array([88, 58])

In [17]:
studentArray["money"]

array([  1.23456788e+10,   1.23456788e+10], dtype=float32)