In [1]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])

In [2]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.shape  #维度，2行，3列

(2, 3)

In [4]:
a.size #多少个元素

6

In [5]:
newa=np.array([[1,2,3],[4,5,6]])
newa

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
newa.shape #维度，2行，3列

(2, 3)

In [7]:
newa.shape=(3,2) #动态调正

In [8]:
newa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
newa.reshape(1,6) #动态调整维度

array([[1, 2, 3, 4, 5, 6]])

In [10]:
newa.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
makea=np.arange(24) #动态创建连续数组
makea

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
makea.reshape(4,6) #不会改变的原来的

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
makea=makea.reshape(3,8)
makea

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [17]:
makea.ndim  #维度的维数

2

In [18]:
makea=makea.reshape(2,3,4) #三维数组
makea

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
makea.ndim  #维度的维数

3

In [20]:
makea.itemsize #这一数组属性返回数组中每个元素的字节单位长度。

4

In [21]:
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)

1


In [22]:
x = np.array([1,2,3,4,5], dtype = np.int64)  
print (x.itemsize)

8


In [23]:
print(x.flags)
#| 序号 | 属性及描述 | 
'''
| --- | --- |
| 1. | `C_CONTIGUOUS (C)` 数组位于单一的、C 风格的连续区段内 |
| 2. | `F_CONTIGUOUS (F)` 数组位于单一的、Fortran 风格的连续区段内 |
| 3. | `OWNDATA (O)` 数组的内存从其它对象处借用 |
| 4. | `WRITEABLE (W)` 数据区域可写入。 将它设置为`flase`会锁定数据，使其只读 |
| 5. | `ALIGNED (A)` 数据和任何元素会为硬件适当对齐 |
| 6. | `UPDATEIFCOPY (U)` 这个数组是另一数组的副本。当这个数组释放时，源数组会由这个数组中的元素更新
 '''

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
