In [5]:
import numpy as np 
x = np.empty([3,12], dtype =  int)  #随机抓取内存，没有清零，
x

array([[3801155, 5570652, 6619251, 7536754, 5505116, 6881395, 6750318,
        7667816, 2949217, 6881401, 6488174, 6619240],
       [6750318, 3014748, 7340137, 7602297, 7274600, 6029422, 7471216,
        6684783, 7077993, 6226021, 6619236, 6357094],
       [7078005, 6029428, 6881384, 7602291, 7471215, 3014777, 7405683,
        6881388, 6619252, 6946861, 7667823, 7209074]])

In [6]:
x=np.zeros(15) #清零的实数，15个
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.])

In [7]:
x=np.zeros( (15,),dtype=np.int) #清零的整，15个
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
x=np.zeros((3,3),dtype=([("tall","f4"),("age","i4"),("money","f4")]))
#自定义类型，创建数组，初始化

In [9]:
x

array([[( 0., 0,  0.), ( 0., 0,  0.), ( 0., 0,  0.)],
       [( 0., 0,  0.), ( 0., 0,  0.), ( 0., 0,  0.)],
       [( 0., 0,  0.), ( 0., 0,  0.), ( 0., 0,  0.)]], 
      dtype=[('tall', '<f4'), ('age', '<i4'), ('money', '<f4')])

In [10]:
x["tall"]

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [11]:
x=np.ones(5)
x

array([ 1.,  1.,  1.,  1.,  1.])

In [12]:
x=np.ones([5,5],dtype=np.int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])