In [8]:
import numpy as np 
x=[1,2,3,4,5]
Array1=np.asarray(x)
print(Array1)

[1 2 3 4 5]


In [9]:
Array1=np.asarray(x,dtype=np.float)
print(Array1)

[ 1.  2.  3.  4.  5.]


In [10]:
y=(1,2,3,4,5)
Array1=np.asarray(y)
print(Array1)

[1 2 3 4 5]


In [4]:
z=[(1,2,3,4,5),(6,7,8)]
Array1=np.asarray(z)
print(Array1)

[(1, 2, 3, 4, 5) (6, 7, 8)]


In [12]:
myname="huangjianjian"
mynamenp=np.frombuffer(myname,dtype="S1")
print(mynamenp) # 'str' object has no attribute '__buffer__'

AttributeError: 'str' object has no attribute '__buffer__'

In [13]:
mylist=[x for x  in range(10)]
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
it=iter(mylist)
Xarray=np.fromiter(it,dtype=np.int8) #根据迭代器创建数组
print(Xarray)

[0 1 2 3 4 5 6 7 8 9]
