In [1]:
import numpy as np
x = np.arange(5)  #创建数组序列0-5

In [2]:
x

array([0, 1, 2, 3, 4])

In [3]:
x = np.arange(1,10) #创建数组1-9
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x = np.arange(1,100,3)#创建数组1-100，3为步长
x

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [5]:
x = np.arange(1,100,3,dtype=np.float)#创建数组1-100，3为步长 ,实数
x

array([  1.,   4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.,
        34.,  37.,  40.,  43.,  46.,  49.,  52.,  55.,  58.,  61.,  64.,
        67.,  70.,  73.,  76.,  79.,  82.,  85.,  88.,  91.,  94.,  97.])

In [6]:
y=np.linspace(10,20,10)
print(y)

[ 10.          11.11111111  12.22222222  13.33333333  14.44444444
  15.55555556  16.66666667  17.77777778  18.88888889  20.        ]


In [7]:
y=np.linspace(10,20,2)#此函数类似于`arange()`函数。 在此函数中，指定了范围之间的均匀间隔数量，而不是步长
print(y)

[ 10.  20.]


In [8]:
y=np.linspace(10,20,5)
print(y)

[ 10.   12.5  15.   17.5  20. ]


In [9]:
y=np.linspace(10,20,5,endpoint=False) #是否包含最后一个
print(y)

[ 10.  12.  14.  16.  18.]


In [10]:
y=np.linspace(10,20,5,endpoint=False,retstep=True) #是否包含最后一个
print(y) #retstep插入切割的步长

(array([ 10.,  12.,  14.,  16.,  18.]), 2.0)


In [21]:
z=np.logspace(1.0,2.0,num=3)   #其中包含在对数刻度上均匀分布的数字。 刻度的开始和结束端点是某个底数的幂，通常为 10。
z#默认的底数是10

array([  10.       ,   31.6227766,  100.       ])

In [24]:
z=np.logspace(1.0,2.0,num=20,base=5)   #其中包含在对数刻度上均匀分布的数字。 刻度的开始和结束端点是某个底数的幂，通常为 10。
z#默认的底数是10, 从5^1  发展到5^2，平方的刻度3，指数级增长

array([  5.        ,   5.441992  ,   5.92305539,   6.44664402,
         7.01651704,   7.63676592,   8.31184382,   9.04659752,
         9.84630227,  10.71669965,  11.66403876,  12.69512113,
        13.81734953,  15.03878113,  16.36818533,  17.81510674,
        19.38993369,  21.10397281,  22.96953026,  25.        ])

In [25]:
z=np.logspace(1,10,num=10,base=2) # 2^1  --->2^10
'''
`logspace`函数的输出由以下参数决定：

| 序号 | 参数及描述 |
| --- | --- |
| 1. | `start` 起始值是`base ** start` |
| 2. | `stop` 终止值是`base ** stop` |
| 3. | `num` 范围内的数值数量，默认为`50` |
| 4. | `endpoint` 如果为`true`，终止值包含在输出数组当中 |
| 5. | `base` 对数空间的底数，默认为`10` |
| 6. | `dtype` 输出数组的数据类型，如果没有提供，则取决于其它参数 |
'''

In [26]:
z

array([    2.,     4.,     8.,    16.,    32.,    64.,   128.,   256.,
         512.,  1024.])