In [1]:
import numpy as np

In [2]:
myarray=np.arange(10)  
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
s=slice(2,7,2)  #2-7之间，不包含7，每次+2
print(type(s)) #class 'slice,索引，
myarray[s]

<class 'slice'>


array([2, 4, 6])

In [8]:
print(myarray[2:7:3]) #等价关系  [2:7:3]  slice(2,7,2)

[2 5]


In [10]:
print(myarray[2:7:1])

[2 3 4 5 6]


In [11]:
print(myarray[2:-1:1])

[2 3 4 5 6 7 8]


In [12]:
print(myarray[::1])

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(myarray[::]) #省略  第一个，最后一个，步长

[0 1 2 3 4 5 6 7 8 9]


In [14]:
myarray[4]

4

In [15]:
myarray[0]

0

In [16]:
myarray[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
myarray[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [18]:
myarray[2:5]

array([2, 3, 4])

In [19]:
myarray=np.arange(20)
myarray.shape=(4,5)
myarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
myarray[0] #取出2维数组的1维数组

array([0, 1, 2, 3, 4])

In [21]:
myarray[1]

array([5, 6, 7, 8, 9])

In [23]:
myarray[2]

array([10, 11, 12, 13, 14])

In [24]:
myarray[2][1:3] #取出2唯数组中的某一行的某一个序列

array([11, 12])

In [26]:
myarray[0:2]  #2维数组

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
myarray[0:2] [0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
myarray[0] [0:2]

array([0, 1])

In [29]:
myarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
myarray[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
myarray[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
myarray[::2] #2代表步长

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [33]:
myarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
myarray[1,...] #取出第二行

array([5, 6, 7, 8, 9])

In [36]:
myarray[...,1] #取出第二列

array([ 1,  6, 11, 16])

In [37]:
myarray[1:3,...] #1-2行

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
myarray[...,1:3] #1-2列

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])