In [4]:
import numpy as np
myarray=np.array([[0,1,2],[3,4,5],[6,7,8]])
myarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
mydata=myarray[[0,1,2],[0,1,2]]  # 00,11,22 ,xy坐标
mydata

array([0, 4, 8])

In [7]:
mydata=myarray[[0,1,2],[2,1,0]]  # 02,11,20 ,xy坐标
mydata

array([2, 4, 6])

In [8]:
myarray=np.arange(12)
myarray.shape=(4,3)
myarray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
rows=np.array([[0,0],[3,2]])
cols=np.array([[0,2],[0,2]])

In [22]:
print(rows) #行
print(cols) #列
print(myarray[rows,cols])#矩阵的乘法

[[0 0]
 [3 2]]
[[0 2]
 [0 2]]
[[0 2]
 [9 8]]


In [23]:
myarray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
print(myarray[1:3,1:3]) #联合挖掘，1:3代表1-3之间

[[4 5]
 [7 8]]


In [29]:
print(myarray[1:3,[0,2]]) #联合挖掘， ,[0,1,2]代表列

[[3 5]
 [6 8]]


In [30]:
myarray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
myarray[myarray<5]  #取出小于5

array([0, 1, 2, 3, 4])

In [32]:
myarray[myarray>5] #取出大于5

array([ 6,  7,  8,  9, 10, 11])

In [33]:
myarray[myarray %2==0] #偶数

array([ 0,  2,  4,  6,  8, 10])

In [34]:
myarray[myarray %2!=0] #奇数

array([ 1,  3,  5,  7,  9, 11])

In [35]:
a = np.array([np.nan,  1,2,np.nan,3,4,5])  #nan  not a number  5/0
print (a[~np.isnan(a)])#筛选无效数据

[ 1.  2.  3.  4.  5.]


In [37]:
a = np.array([1,  2+6j,  5,  3.5+5j])  
print (a[np.iscomplex(a)]) #只要复数

[ 2.0+6.j  3.5+5.j]
